apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakelogin
  labels:
    app: fakelogin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fakelogin
  template:
    metadata:
      labels:
        app: fakelogin
    spec:
      containers:
        - name: fakelogin
          image: rafaelcecchin/fakelogin

          readinessProbe:
            httpGet:
              path: /healthz.php
              port: 80
            periodSeconds: 3
            failureThreshold: 1

          # livenessProbe:
          #   httpGet:
          #     path: /healthz.php
          #     port: 80
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   timeoutSeconds: 1
          #   successThreshold: 1

          volumeMounts:
            - mountPath: /var/www/html/_env
              name: config
      volumes:
        - name: config
          configMap:
            name: fakelogin-env
