apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakelogin
  labels:
    app: fakelogin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fakelogin
  template:
    metadata:
      labels:
        app: fakelogin
    spec:
      containers:
        - name: fakelogin
          image: rafaelcecchin/fakelogin
          startupProbe:
            httpGet:
              path: /healthz.php
              port: 80
            periodSeconds: 3
            failureThreshold: 20
          resources:
            requests:
              cpu: 100m
              memory: 45Mi
            limits:
              cpu: 650m
              memory: 80Mi

          volumeMounts:
            - mountPath: /var/www/html/_env
              name: config
      volumes:
        - name: config
          configMap:
            name: fakelogin-env
